### ISSUE TITLE
Does it actually work? ValueError: pattern  did not match any tags

### ISSUE THREAD

**Issue by harasimowiczmaciek** [mtkennerly/poetry-dynamic-versioning#1]
Hello

Thank you for making this package.

I am working in project that requires scm versioning, and we decided to use Poetry, however I wasn't able to set it up with your package. There is nothing going on here, so maybe I am naive by making this post, but still I decided to give it a shot. 

I got this error(after running poetry check or poetry shell):

```

[ValueError]
Pattern 'v(?P<base>\d+\.\d+\.\d+)((?P<pre_type>[a-zA-Z]+)(?P<pre_number>\d+))?' did not match any tags

```

I set the code up just like in the documentation, I also check if the tags are actually there (by running git tag command).

```

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

```

I am using Poetry version 1.0.0b1 (the prerelease one). I installed your package both in my global python and inside the poetry shell.

Best regards

**Comment by mtkennerly** [comment]
Hi, @harasimowiczmaciek. I'm really sorry for the delay in responding - somehow I never got a notification from this ticket.

I can't seem to reproduce this with Poetry 1.0.0b1 and plugin 0.1.0. Could you please show me the output of `git tag --sort -creatordate`?

Also, I just released plugin 0.2.0 with support for the latest Poetry pre-release, 1.0.0b2, since there was a change between 1.0.0b1 and 1.0.0b2 that affected the plugin. Could you please try one more time with Poetry 1.0.0b2 and plugin 0.2.0? I added several tests to Travis, including Python 3.5/3.6/3.7/3.8 + Poetry 1.0.0b2 + `pip install poetry`/`get-poetry.py`, so if you still see the problem, it should be easier to narrow down a scenario that's missing test coverage.

I'm subscribed to the ticket now, so I should be able to respond much more promptly 😅

**Comment by xnuinside** [comment]
@harasimowiczmaciek yes it's works well, your tag not match patter)) as it write in error : 'Pattern 'v(..' tag must start with 'v' for example 'v1.1.1'. To work with you tag - you need change pattern and set your own in configuration file.

**Comment by mtkennerly** [comment]
@harasimowiczmaciek, if you still have any issues after the suggestions above, please let me know or open a new ticket.

**Comment by pykong** [comment]
I get the same error with `poetry==1.0.3` and `0.5.0` of this package.
See: https://travis-ci.org/Guake/guake/jobs/651655029#L4141-L4143

**Comment by mtkennerly** [comment]
Hi, @pykong! The default `pattern` setting expects the tags to start with a `v`, which those tags don't have. You can take the default `pattern` from the README and tweak it to remove the `v`.

**Comment by pykong** [comment]
@mtkennerly That worked.
I must have misunderstood PEP440.

**Comment by fredrikaverpil** [comment]
I too got hit by this.

I followed the instructions to simply copy the pattern from the readme and removed the 'v':

```
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern  = "^(?P<base>\d+\.\d+\.\d+)(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?"
```

But this yields:

```
tomlkit.exceptions.InvalidCharInStringError: Invalid character 'd' in string at line 82 col 24
```

I'm now wondering what the best solution is... should I escape all those backslashes?

**Comment by mtkennerly** [comment]
@fredrikaverpil, yep, you just have to escape them to make TOML happy. I can add a note to the README about that.

You can add timestamps and other stuff with `format-jinja-imports`:

```toml
[tool.poetry-dynamic-versioning]
enable = true
format-jinja = """
    {%- if distance == 0 -%}
        {{- base -}}
    {%- else -%}
        {{- base }}.dev{{ distance }}+d{{ datetime.now().strftime('%Y%m%d%H%M%S') -}}
    {%- endif -%}
"""
format-jinja-imports = [
    { module = "datetime", item = "datetime" }
]
```

Produces:

```
0.8.3.dev1+d20200827133158
```

**Comment by fredrikaverpil** [comment]
I believe you forgot the `{{commit}}` above. :)

This works marvelously:

```
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"
format-jinja = """
    {%- if distance == 0 -%}
        {{- base -}}
    {%- else -%}
        {{- base }}.dev{{ distance }}+{{commit}}.d{{ datetime.now().strftime('%Y%m%d%H%M%S') -}}
    {%- endif -%}
"""
format-jinja-imports = [
    { module = "datetime", item = "datetime" }
]
```

**Comment by mtkennerly** [comment]
Yep :D I suppose you'd want `g{{commit}}` to match setuptools_scm exactly.

**Comment by fredrikaverpil** [comment]
Ah, great - thanks for noticing the missing `g`!
