### ISSUE TITLE
Should format-jinja override style like format?

### ISSUE THREAD

**Issue by rberger** [mtkennerly/poetry-dynamic-versioning#100]
I had expected format-jinja to override style if format-jinja is set and style was not set. But that doesn't seem to be the case.

Should it? My use case would like it to.

I would like to have abbreviated SHA as a suffix for non-release but dev build cycles...

**Comment by mtkennerly** [comment]
Hi! `style` should only be enforced if it's explicitly set in your config. Could you give an example of your config, the output you see, and the output you'd like to see?

**Comment by mtkennerly** [comment]
Poetry itself does also enforce some versioning rules. Maybe that's what you were seeing? This can happen even without the plugin installed at all:

```
$ poetry init -n
$ sed -i 's/version =.*/version = "0.1.0x"/' pyproject.toml
$ poetry build
Invalid PEP 440 version: '0.1.0x'
```

If that doesn't help, just let me know, and we can reopen this.
