### ISSUE TITLE
Newlines are changed from LF to CRLF

### ISSUE THREAD

**Issue by Hasenpfote** [mtkennerly/poetry-dynamic-versioning#105]
Hi!
I tried `poetry-dynamic-versioning` v0.21.1 on Windows 10 64bit version.

1. Prepare `pyproject.toml` and `__init__.py` files and set newlines to LF.
2. automatically or manually run `poetry-dynamic-versioning`.
3. `poetry-dynamic-versioning` modifies the `version` and `__version__` variables.

At this time, newlines in files modified by `poetry-dynamic-versioning` are changed from LF to CRLF.
I was confused because I was expecting it to remain LF.
By the way, the sdist `setup.py` file generated by poetry build was LF.
The `poetry version` command, on the other hand, keeps LF after conversion.

In this case, is there an option to not change from LF?

Thank you.

**Comment by mtkennerly** [comment]
Hi! It looks like this is the default behavior of pathlib's `write_text`. Line endings are apparently preserved with `write_bytes`, so I'll switch to that.

**Comment by mtkennerly** [comment]
I just released 0.21.2. Could you let me know if you still see any issues?

**Comment by Hasenpfote** [comment]
v0.21.2 worked perfectly as expected for me.
Thanks for the quick response!

**Comment by Hasenpfote** [comment]
Oops, I accidentally closed the issue.
I will re-open it for your release work.

**Comment by mtkennerly** [comment]
It was alright to close the ticket :) Thanks for confirming that it works!
