### ISSUE TITLE
Wrong git version with develop = true

### ISSUE THREAD

**Issue by APN-Pucky** [mtkennerly/poetry-dynamic-versioning#107]
Hi, 
I am coding two python packages both with `poetry-dynamic-versioning` and occasionally I set `develop = true`, like below:

```
feynml= {path= "../feynml", develop = true }
```

However, this results in the packages specified with path getting the git tag version from the folder of the other project.

I am using version 0.21.3 of  `poetry-dynamic-versioning`.

**Comment by mtkennerly** [comment]
Thanks for reporting this! The fix for this will be included in the next release shortly.
