### ISSUE TITLE
Q: Can I build package only if current commit has tag?

### ISSUE THREAD

**Issue by voronind** [mtkennerly/poetry-dynamic-versioning#108]
I want to build package only if current commit has tag. Can I do this using poetry-dynamic-versioning?

**Comment by mtkennerly** [comment]
Hi! Could you give me a little more context about the intended result? Do you want `poetry build` to fail when there's no tag? Or do you need to detect that there's no tag and avoid trying to run `poetry build` at all?

**Comment by voronind** [comment]
> Hi! Could you give me a little more context about the intended result? Do you want `poetry build` to fail when there's no tag? Or do you need to detect that there's no tag and avoid trying to run `poetry build` at all?

Any of this results. I want to build release only.

**Comment by mtkennerly** [comment]
I would suggest using a wrapper script like this (using [Dunamai](https://github.com/mtkennerly/dunamai) directly):

```
distance=$(dunamai from any --format "{distance}")
if [ "$distance" = "0" ]; then
    poetry build
    poetry publish
fi
```

**Comment by voronind** [comment]
Thank you
