### ISSUE TITLE
Plugin does not see git tags

### ISSUE THREAD

**Issue by AIGeneratedUsername** [mtkennerly/poetry-dynamic-versioning#110]
## Versions

- Poetry 1.3.1
- poetry-dynamic-versioning v0.21.3
- Python 3.10.9

## Description
 "poetry-dynamic-versioning" does not see tags even if I just fetched them (e.g. there is `v0.6.20` tag):
```sh
+ set -e
+ git fetch --tags --depth=1
From https://gitlab.com/<masked>/<masked>/<masked>/<masked>
 * [new tag]         v0.6.20    -> v0.6.20
+ head -n 5
+ git tag -l --sort=-creatordate
v0.6.20
+ poetry config repositories.gitlab-backend-<masked> https://gitlab.com/api/v4/projects/<masked>/packages/pypi
No tags available and fallbacks disabled by strict mode
```

I have this problem only in GitLab CI. Locally the plugin can find tags.

**Comment by mtkennerly** [comment]
Hi! Could you show me the output for these commands on GitLab?

* `git --version`
* `git for-each-ref "refs/tags/**" --format "%(refname)" --sort -creatordate`
* `git for-each-ref "refs/tags/**" --format "%(refname)" --sort -creatordate --merged HEAD`

**Comment by AIGeneratedUsername** [comment]
Thank you for your response. I added your commands to my script. Here is a CI pipeline log:
```bash
+ set -e
+ git --version
git version 2.30.2
+ git fetch --tags --depth=1
From https://gitlab.com/<masked>/<masked>/<masked>/<masked>
 * [new tag]         v0.6.20    -> v0.6.20
+ head -n 5
+ git tag -l --sort=-creatordate
v0.6.20
+ git for-each-ref 'refs/tags/**' --format '%(refname)' --sort -creatordate
refs/tags/v0.6.20
+ git for-each-ref 'refs/tags/**' --format '%(refname)' --sort -creatordate --merged HEAD
+ poetry config repositories.gitlab-backend-<masked> https://gitlab.com/api/v4/projects/<masked>/packages/pypi
No tags available and fallbacks disabled by strict mode
```

**Comment by AIGeneratedUsername** [comment]
I use fetch, not clone, Fixed by changing an environment variable from `GIT_DEPTH: 1` to `GIT_DEPTH: 50`.

Anyway, I still wonder why if `git for-each-ref 'refs/tags/**' --format '%(refname)' --sort -creatordate` (without `--merged HEAD`) was able to read a git tag, why can not "poetry-dynamic-versioning" use the same command?

**Comment by mtkennerly** [comment]
> Anyway, I still wonder why if git for-each-ref 'refs/tags/**' --format '%(refname)' --sort -creatordate (without --merged HEAD) was able to read a git tag, why can not "poetry-dynamic-versioning" use the same command?

The plugin uses the command with `--merged` to get the most accurate data.

> Fixed by changing an environment variable from GIT_DEPTH: 1 to GIT_DEPTH: 50.

The plugin does expect to have the full Git history available, so you may eventually need to increase that or get the full history with `0`.
