### ISSUE TITLE
Error if `git` is not installed

### ISSUE THREAD

**Issue by MaxG87** [mtkennerly/poetry-dynamic-versioning#112]
Thank you for this great plugin. It helped to get rid of some complexity in our Gitlab build pipeline.

However, there is a minor issue. It seems as if the plugin only works in `git` projects if  `git` is installed. If `git` is not installed, as is the case in the containers used by the Gitlab runner I am using, there will be a crash of unclear source.

The error reported will be _Error: Unable to detect version control system._ It took some guesswork to figure out that this is because `git` was not installed. In the CI/CD context, I cannot connect to the container to inspect it.

I produced a self-contained script that reproduces the error:
```
#!/usr/bin/env bash

set -euo pipefail

export DOCKER_BUILDKIT=1
TARGETDIR=$(mktemp -d)
cd "$TARGETDIR"

echo >Dockerfile 'FROM python:latest

WORKDIR /project

RUN apt update && apt install --assume-yes git
RUN python -m pip install "poetry==1.3.2" poetry-dynamic-versioning

RUN git init && \
    git config --global user.email "erika@example.com" && \
    git config --global user.name "Erika Mustermann"

RUN poetry init --name mwe --description "Minimum Working Example" --no-interaction && \
    poetry version v0.0.0 && \
    mkdir -p src/mwe/ && \
    touch src/mwe/__init__.py README.md


RUN git add . && \
    git commit -m "Initial commit" && \
    git tag v1.0.0
RUN apt purge --assume-yes git && \
    apt autoremove --assume-yes
CMD ["poetry", "run", "poetry-dynamic-versioning"]
'
DOCKER_BUILDKIT=1 docker build . -t testimg
docker run -t testimg
```

**Comment by mtkennerly** [comment]
Hi! This is working as intended, since the plugin relies on the official Git client to obtain info for Git projects. Is your concern just that the error message or documentation should be improved to make this more obvious?

**Comment by MaxG87** [comment]
While I would welcome if the `git` client was not relied on, I understand that you do not want to change that. My main concern was that the error message could be improved to point out that the client should be installed.

**Comment by mtkennerly** [comment]
For what it's worth, this issue applies to the default configuration, which has `vcs = "any"`, so the plugin doesn't know which VCS to expect. If you set `vcs = "git"`, then the error is more specific: `Unable to find 'git' program`.

Dunamai v1.16.0 includes this change for `any`:

```
$ PATH=. /c/opt/python/3.10/Scripts/dunamai from any
Unable to detect version control system. Not installed: Git, Mercurial, Darcs, Subversion, Bazaar, Fossil, Pijul.

$ PATH=/c/opt /c/opt/python/3.10/Scripts/dunamai from any
Unable to detect version control system. Checked: Darcs, Fossil, Pijul. Not installed: Git, Mercurial, Subversion, Bazaar.
```
