### ISSUE TITLE
Enable plugin with shell

### ISSUE THREAD

**Issue by Cologler** [mtkennerly/poetry-dynamic-versioning#117]
For example, when the user executes `poetry dynamic-versioning --enable`, it auto modify the `pyproject.toml` and enables the `poetry_dynamic_versioning.backend` build system.

**Comment by mtkennerly** [comment]
Thanks for the suggestion :) I've asked on the Poetry repo about how to add subcommands to a plugin's CLI: https://github.com/orgs/python-poetry/discussions/8091
