### ISSUE TITLE
Poetry 1.4 compatibility

### ISSUE THREAD

**Issue by couling** [mtkennerly/poetry-dynamic-versioning#119]
It looks like poetry 1.4 has broken something with compatibility.

Previously with poetry 1.3 `poetry install` and `poetry build` would select the correct version number from git tags.  But with poetry 1.4 (I'm on `1.4.2`) this now just reports the version as 0.0.0

The current work around to this is to:
 - build with `python -m build`
 - publish with `twine`

It would be lovely to have `poetry build` and `poetry publish` working again.

Affects poetry-dynamic-versioning 0.21.4

**Comment by mtkennerly** [comment]
Hi! Could you confirm if poetry-dynamic-versioning is listed in the output of `poetry self show` and if you installed poetry-dynamic-versioning with the `[plugin]` feature? The tests are still passing with 1.4.2, so there may be something else going on here. I wonder if the plugin got wiped out when you upgraded Poetry?

**Comment by couling** [comment]
Hmm No. apologies this was a false positive.

I think what threw me off is that `poetry update` modifies `pyroject.toml` disabling the plugin.
