### ISSUE TITLE
"pip wheel" does not see poetry-dynamic-versioning

### ISSUE THREAD

**Issue by kalfa** [mtkennerly/poetry-dynamic-versioning#12]
Hi,
 I'm trying to put things together and check how pyproject can be really help us.

I might be completely wrong here, and happy to be corrected:

when I run ```pip wheel --use-pep517  .``` on a project with pyproject.toml which defines a non setuptools build-backend (e.g. it uses poetry), then the building machine trigger by pip will delegate the building to the specified modules, via the entry point.

given that, I expect when I run the command, that also poetry-dynamic-versioning is triggered, the same way it is when I use 'poetry build'.

while when i use pip, the produced wheel packge has the version specified in the toml file, not the version computed by the dynamic plugin (which works fine if triggered by poetry)

poetry API is called as expected.

**Comment by mtkennerly** [comment]
I'll need to look into adding support for this. Currently, the plugin only patches the Poetry console code in order to activate itself, whereas what you're doing is skipping Poetry's CLI and just using its core library, so the patched code never triggers.

**Comment by kalfa** [comment]
I can use poetry cli, or your cli before runnin pip, in my cicd env, and
would work either way.

Unless this is the direction you want to go for your project, it's ok to
not support it.

To be honest I like to be able to have a unified cli for generic package
operations, but that's not mandatory.

I guess when poetry will support plugins out of the box, it will be clearer.

**Comment by mtkennerly** [comment]
This is now supported in 0.8.0.

**Comment by kalfa** [comment]
Thanks!
