### ISSUE TITLE
Allow poetry-install to run without repository

### ISSUE THREAD

**Issue by BlackZork** [mtkennerly/poetry-dynamic-versioning#122]
I have to bind-mount whole .git repository when building docker development images.

I would like to store output of "poetry version -s" into some POETRY_DYNAMIC_VERSIONING_FORCE_VERSION and pass it to docker with sources only. setuptool_scm has this feature as SETUPTOOLS_SCM_PRETEND_VERSION.

**Comment by mtkennerly** [comment]
You can use `POETRY_DYNAMIC_VERSIONING_BYPASS` :) It's documented here: https://github.com/mtkennerly/poetry-dynamic-versioning#environment-variables

**Comment by BlackZork** [comment]
Yes, but I would like to return valid version from services that run from development image, not hardcoded "1".

**Comment by mtkennerly** [comment]
I'm not sure what you mean. You can do `export POETRY_DYNAMIC_VERSIONING_BYPASS=$(poetry version -s)` like you mentioned in the initial description. It just uses whatever value you set.

**Comment by BlackZork** [comment]
Ok, I misunderstood docs. I thought that it uses always "1", not value of env variable. Maybe it youd be good to clarify it in docs? Something like:

```Use this to bypass the VCS mechanisms and use a static version passed as value of environment variable instead```

**Comment by mtkennerly** [comment]
Yeah, that's a good suggestion. Added in 718b19a515f43a66bc3b4bb2e6b0d9dc87c7181c.
