### ISSUE TITLE
POETRY_DYNAMIC_VERSIONING_BYPASS should not affect dependencies.

### ISSUE THREAD

**Issue by BlackZork** [mtkennerly/poetry-dynamic-versioning#124]
Scenario:

1. A python lib mylib uses poetry-dynamic-versioning
2. A python project myproject has mylib dependecy on git tag:

```
[tool.poetry.dependencies]
python = "~3.9"
mylib = { git = "ssh://repouser@host/mylib", tag = "0.9.0" }
```

running `POETRY_DYNAMIC_VERSIONING_BYPASS=1 poetry install` installs mylib with version=1

Setting POETRY_DYNAMIC_VERSIONING_BYPASS should not affect dependencies.

Possible workaround:
```
poetry install --no-root
POETRY_DYNAMIC_VERSIONING_BYPASS=1 poetry install
```
(I moved away from adding git deps to tool.poetry.dependencies, so I have not tested it.)

**Comment by mtkennerly** [comment]
Thanks for bringing this up. I could add another bypass option that supports something like `mylib=0.1.0;dep2=0.2.0` so that you can set them separately.

**Comment by BlackZork** [comment]
I cannot find any realistic scenario when this could be needed. I mean - changing version of some dependency library.
By default dependency should not be touched. I would rather change env name to POETRY_DYNAMIC_VERSIONING_BYPASS_FOR_$(uppercase_project_name) and depreciate POETRY_DYNAMIC_VERSIONING_BYPASS.

**Comment by mtkennerly** [comment]
The scenario is that your dependencies could also be using poetry-dynamic-versioning. If the plugin ignored those dependencies, then they would use the placeholder version from pyproject.toml.

Normally, the plugin computes the correct dynamic version for each dependency that uses the plugin, and it ignores any dependencies that don't use it.

**Comment by BlackZork** [comment]
> The scenario is that your dependencies could also be using poetry-dynamic-versioning. If the plugin ignored those dependencies, then they would use the placeholder version from pyproject.toml.

myproject has tag 0.5.4
mylib has tag 0.9.0

I am doing install in docker container witohut .git.
I override version with POETRY_DYNAMIC_VERSIONING_BYPASS=0.5.4 for `myproject`. I do not want to override it for `mylib` with the same (wrong) version.

Maybe there are real-time scenarios when myproject and mylib are from different git repositories and uses the same version number, but it is unlikely. In most cases POETRY_DYNAMIC_VERSIONING_BYPASS means "override version number for myproject and nothing else". 

Support for `mylib=0.1.0;dep2=0.2.0` is a good idea, but if I set POETRY_DYNAMIC_VERSIONING_BYPASS=0.5.4 it should behave like POETRY_DYNAMIC_VERSIONING_BYPASS="myproject=0.5.4" without touching mylib.

**Comment by mtkennerly** [comment]
Right, I understand your concern. The only limitation is that, if mylib also uses the plugin and we don't know what version to give it, then we can only either give it the placeholder from its pyproject.toml (usually 0.0.0) or the same version as myproject. Both are wrong, essentially, and we can't give it the right version without some extra input.

If you set `POETRY_DYNAMIC_VERSIONING_BYPASS=0.5.4`, would you prefer that mylib default to 0.0.0 or 0.5.4? I think changing it to use 0.0.0 is probably better, but I just want to be clear that mylib *can't* default to 0.9.0 automatically if it also uses the plugin.

**Comment by BlackZork** [comment]
> I just want to be clear that mylib _can't_ default to 0.9.0 automatically if it also uses the plugin.

I would prefer a solution similar to setuptools and set POETRY_DYNAMIC_VERSIONING_BYPASS_FOR_MYPROJECT=0.5.4. My lib will check POETRY_DYNAMIC_VERSIONING_BYPASS_FOR_MYLIB and because it is not set then it will set version from git tag.

**Comment by mtkennerly** [comment]
Ah, so the main difference here is that `POETRY_DYNAMIC_VERSIONING_BYPASS` was introduced for a use case where dynamic versioning should be completely disabled, whereas in your case it's okay to keep using dynamic versioning for dependencies only.

I think this combination of options could satisfy both:

* "I just want to set a specific version easily. I don't have path/SSH dependencies, or I don't care about their versions. I don't want to deal with dynamic versioning right now."
  * `POETRY_DYNAMIC_VERSIONING_BYPASS=0.1.0`
* "I want to turn off dynamic versioning for a specific package, but others can keep using it."
  * `POETRY_DYNAMIC_VERSIONING_OVERRIDE="myproject=0.1.0"`
* "I want to turn off dynamic versioning completely and have full control over all versions used."
  * `POETRY_DYNAMIC_VERSIONING_BYPASS=0.0.0` combined with `POETRY_DYNAMIC_VERSIONING_OVERRIDE="myproject=0.1.0;mylib=0.2.0"`
