### ISSUE TITLE
Is the `version` needed in pyproject.toml?

### ISSUE THREAD

**Issue by 2m** [mtkennerly/poetry-dynamic-versioning#14]
I am trying `poetry-dynamic-versioning` on MacOS and I have successfully installed it.

I am able to run the CLI tool and I get the expected output:

```
─╼ poetry-dynamic-versioning
Version: 0.1.4-post.4+6f0ae10
Files with substitutions: none
```

But if I run `poetry build` I see the output with the version set in `pyproject.toml`:

```
─╼ poetry build
Building project (0.0.0)
 - Building sdist
 - Built project-0.0.0.tar.gz

 - Building wheel
 - Built project-0.0.0-py3-none-any.whl
```

But If I remove `version` from `pyproject.toml` then I get the following:

```
─╼ poetry build
[RuntimeError]
The Poetry configuration is invalid:
  - 'version' is a required property
```

**Comment by mtkennerly** [comment]
It appears that I introduced a defect in 0.8.0 where CLI mode wouldn't update pyproject.toml. Although I had a test for it, there was also a defect in the test, so it passed when it shouldn't have. I've just released 0.8.1 to fix that.

That said, the `version` field is indeed required, based on the design of Poetry. The plugin only makes `poetry build` automatically set the version if you enable the plugin in the config:

```toml
[tool.poetry-dynamic-versioning]
enable = true
```

**Comment by 2m** [comment]
Thank you for a quick fix!

With `0.8.1` the version is being changed in `pyproject.toml` when I run CLI mode. 

However if I run `poetry build` I see that the version is taken from `pyproject.toml` and not dynamically generated from the git history.

**Comment by mtkennerly** [comment]
My first guess would be that the plugin's .pth file isn't being recognized, but I'm not sure how to reproduce this. I don't necessarily think it's Mac-specific since #8 reported that the plugin works on Mac, although I don't have a Mac system to test personally. What happens if you add `; print("test")` in zzz_poetry_dynamic_versioning.pth in site-packages and then run Python?

**Comment by 2m** [comment]
Sorry for dropping the ball on this one. Your note gave me a needed hint and I was able to figure out what was going on. Its related to a bit of a mess when it comes to python version management in MacOS and brew.

So I originally installed this plugin with `pip3 install -U poetry-dynamic-versioning`. However that used Python 3.7 under `/usr/local/Cellar/python/3.7.7`. However I also have Python 3.8 under `/usr/local/Cellar/python@3.8/3.8.2` which my project is using.

So after installing it to the correct global python installation it works fine now:

```
/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install poetry-dynamic-versioning
```

**Comment by mtkennerly** [comment]
Gotcha. Thanks for following up!

**Comment by max-sixty** [comment]
To the extent I'm not the only one who wasn't sure the answer to this without searching closed issues, it would be great to include this in the readme.

Thanks for the excellent project!

**Comment by mtkennerly** [comment]
@max-sixty Sounds reasonable to me \:) I just added this note:

> Poetry's typical `version` setting is still required in `[tool.poetry]`, but you are encouraged to use `version = "0.0.0"` as a standard placeholder.

Glad you like the project!

**Comment by max-sixty** [comment]
Thank you v much @mtkennerly
