### ISSUE TITLE
Question about substitution with `pip install -e .`

### ISSUE THREAD

**Issue by jsolbrig** [mtkennerly/poetry-dynamic-versioning#146]
I'm trying to use `poetry-dynamic-versioning` with a project that I routinely install via `pip install -e .`. I do not use the Poetry CLI. I'm using substitution in `package/_version.py`. It is important for a few reasons that, even when installed using `-e`, the version is correctly reflected in that version file.

Is there a way to get `poetry-dynamic-versioning` to leave the substitutions in place rather than reverting them when the plugin is disabled?

**Comment by mtkennerly** [comment]
You're right that this hadn't been supported. Although you could run the `poetry-dynamic-versioning` CLI on its own to leave the changes in place, that would leave the changes in *all* files (including pyproject.toml), and if you're not using the Poetry CLI anyway, then you probably wouldn't want to add an extra command just for this.

[v1.1.0](https://github.com/mtkennerly/poetry-dynamic-versioning/releases/tag/v1.1.0) now includes this functionality, and I gave an example of how to use it in [#147](https://github.com/mtkennerly/poetry-dynamic-versioning/issues/147#issuecomment-1742101060) (`persistent-substitution = true`).
