### ISSUE TITLE
Issue with File Substitution during poetry build with poetry-dynamic-versioning

### ISSUE THREAD

**Issue by niniack** [mtkennerly/poetry-dynamic-versioning#148]
### Description:
I am encountering an unexpected behavior when using poetry build in conjunction with the poetry-dynamic-versioning plugin. While the build process correctly outputs the project with the version based on my git tag, it does not update the version in the specified files (pyproject.toml, *_version.py), leaving them at the placeholder "0.0.0".

### Steps to Reproduce:
1. Install poetry using the following command:
   ```
   curl -sSL https://install.python-poetry.org | python3 -
   ```
2. Install dynamic versioning using the following command:
   ```
   ${XDG_DATA_HOME:-~/.local/share}/pypoetry/venv/bin/pip install poetry-dynamic-versioning
   ```
3. Run poetry build.

### Expected Behavior:
The specified files should have their version placeholders substituted with the correct version from the git tag.

### Actual Behavior:
The version in the specified files remains at the placeholder "0.0.0".

### Additional Information:
- Running poetry dynamic-versioning separately does update those files as expected.
- Here is my pyproject.toml file for reference:
   ```
   [tool.poetry]
   name = "MY_PROJECT_NAME"
   version = "0.0.0"
   description = ""
   license = "MIT"
   authors = [""]
   readme = "README.md"
   packages = [{include = "MY_PROJECT_NAME"}]

   [tool.poetry.dependencies]
   python = "^3.7"

   [tool.poetry-dynamic-versioning]
   enable = true
   vcs = "git"
   style = "pep440"

   [tool.poetry-dynamic-versioning.substitution]
   folders = [
     { path = "[MY_PROJECT_NAME]", files = ["_version.py"] }
   ]
   ```

### Question:
Is it expected for the plugin not to perform substitution when running poetry build?

### Environment:
- **Poetry Version:** 1.6.1
- **Poetry-Dynamic-Versioning Version:** 1.0.1
- **OS:** Pop!_OS 22.04 (Linux)
- **Python Version:** 3.10.6

**Comment by mtkennerly** [comment]
> Is it expected for the plugin not to perform substitution when running poetry build?

The plugin will modify them, but only temporarily, so that the modified versions are included in the sdist and wheel artifacts. After the build artifacts are produced, the plugin reverts the files in the repository.

If you'd like to leave the changes in place, then you can run the `poetry dynamic-versioning` command.

**Comment by niniack** [comment]
Thanks for the quick response! Good to know
