### ISSUE TITLE
Wheel file name not matching version from pyproject.toml

### ISSUE THREAD

**Issue by jaanisfehling** [mtkennerly/poetry-dynamic-versioning#151]
The relevant parts of my pyproject.toml file look like this:
```
[tool.poetry]
name = "somepackage"
version = "1.3.1"
description = "Python module for something."
authors = ["SomeAuthor"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
metadata = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```
Running `poetry build` generates a wheel file with the following name: `somepackage-1.3.0.post66+fbb0990-py3-none-any.whl`
Why is it downgrading the version to 1.3.0 when I specified 1.3.1 in pyproject.toml?

**Comment by jaanisfehling** [comment]
I think it had to do with using `poetry build` inside the poetry venv of the project.

**Comment by mtkennerly** [comment]
Hi! The dynamic version is based on Git tags only, without any relation to the version in pyproject.toml. In this case, it looks like it's finding a `v1.3.0` tag, but not a `v1.3.1` tag.
