### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION vs POETRY_DYNAMIC_VERSIONING_BYPASS

### ISSUE THREAD

**Issue by APN-Pucky** [mtkennerly/poetry-dynamic-versioning#161]
According to https://projects.gentoo.org/python/guide/distutils.html#setuptools-scm-flit-scm-hatch-vcs-pdm-backend-and-snapshots setuptools_scm (and thereby flit_scm, hatch-vcs, pdm-backend) can be skipped via `SETUPTOOLS_SCM_PRETEND_VERSION` the variable, does `poetry-dynamic-versioning` use that too or only `POETRY_DYNAMIC_VERSIONING_BYPASS` for desired effect?

**Comment by mtkennerly** [comment]
Hi! This plugin only uses the `POETRY_DYNAMIC_VERSIONING_*` environment variables. It does not use `SETUPTOOLS_SCM_PRETEND_VERSION`.

Incidentally, from that page, it looks like pdm-backend also uses its own variable:

> The [pdm-backend](https://pypi.org/project/pdm-backend/) package reinvents its own SCM version support, and unlike setuptools_scm, it uses 0.0.0 rather than throwing an error when the version cannot be determined. The override for this backend can be set using a similarly purposed environment variable:

> ```export PDM_BUILD_SCM_VERSION=${PV}```

**Comment by APN-Pucky** [comment]
Thanks. When I get to it I might request adding `POETRY_DYNAMIC_VERSIONING_`  to the gentoo docs too then.
