### ISSUE TITLE
Whl files generated by poetry build do not contain the static version files specific in substitiution

### ISSUE THREAD

**Issue by vancromy** [mtkennerly/poetry-dynamic-versioning#163]
Hello,

I have a use case where I do not want to git track my version file and instead want it to be generated on install (regardless of whether poetry or pip are used). If I run `poetry install` the desired `_version.py` file is created and has the correct version. But if I run `pip install path-to-poetry-built-wheel.whl` that file is not created and I get import issues in my package. I have also unzipped the poetry generated wheel file and cannot find the `_version.py` file in the wheel.

I installed the plugin with `poetry self add ...` and here is my pyproject.toml file:
```
[tool.poetry]
name = "random-package"
version = "0.0.0"
readme = "README.md"
packages = [
  {include = "random", from = "src"},
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
latest-tag = true
style = "semver"
pattern = "default-unprefixed"

[tool.poetry-dynamic-versioning.substitution]
files = ["src/random/pacakge/_version.py"]

[tool.poetry-dynamic-versioning.files."src/random/package/_version.py"]
persistent-substitution = true
initial-content = """
  # These version placeholders will be replaced later during substitution.
  __version__ = "0.0.0"
  __version_tuple__ = (0, 0, 0)
"""
```

**Comment by mtkennerly** [comment]
> I have also unzipped the poetry generated wheel file and cannot find the _version.py file in the wheel.

I'm not able to reproduce that behavior. I see the generated file in the wheel, and the wheel's RECORD file also has an entry for it.

I'm using Poetry 1.5.1 and Python 3.10.7 on Windows 11. What's your environment?

> I installed the plugin with `poetry self add ...`

Just to confirm, did you specify the `[plugin]` feature? (`poetry self add "poetry-dynamic-versioning[plugin]"`)

**Comment by vancromy** [comment]
Hi @mtkennerly, thanks for the quick reply. 

I am running macOS 14.2.1 (BuildVersion 23C71) and using pyenv installed python version 3.11.5.

I just reproed it with the same config as above. The `._version.py` file is created after a `poetry install` but does not exist in the built wheels. See attached screenshot: 
![image](https://github.com/mtkennerly/poetry-dynamic-versioning/assets/59556820/117ea7f8-a4ec-45e5-b168-8b00d053528f)

**Comment by mtkennerly** [comment]
Good catch! I've added a note to the README.
