### ISSUE TITLE
[Question] How can I use poetry version with this plugin?

### ISSUE THREAD

**Issue by irux** [mtkennerly/poetry-dynamic-versioning#17]
Hello, I would like to know if I can use poetry version patch (for example) and then the plugin is going to update everything(__init__.py, pythonprojec.toml, etc). I would like that after a poetry version command it will create that version, tag it with a git tag and push it. After that, I can use poetry publish to upload my package. 

Does this plugin support that behaviour? 

thank you!

**Comment by mtkennerly** [comment]
Hi! What you're describing isn't really how the plugin is meant to be used. Essentially, when using this plugin, `git tag v1.2.3` replaces `poetry version 1.2.3` - which is to say, just by setting a tag, it will automatically be used as the version when you run `poetry build` and other commands.

What you're looking for (where you run a command, and it creates a tag for you and commits the version change) sounds more similar to [bumpversion](https://github.com/peritus/bumpversion).
