### ISSUE TITLE
Push to PyPI, even in dirty mode

### ISSUE THREAD

**Issue by wabiloo** [mtkennerly/poetry-dynamic-versioning#171]
Hi,

I have a question related to https://github.com/mtkennerly/poetry-dynamic-versioning/issues/141.

I understand that if I create a git tag and then build and publish, then the version will be in the "right" format for PyPI to accept it (eg. "v0.1.2").
However this does not work is I'm in a dirty state. Which is often the case (various files that have not been added to git yet, because they're experiments that are not yet worth adding).

Is there a way to have the dirty flag "removed" when doing publish (but I still want it when I just do a local build)?

**Comment by mtkennerly** [comment]
Hi! Would it be enough to just do `git stash && poetry publish --build && git stash pop`? Or if they're long-term untracked files, then perhaps you could group them together in a `.gitignore`d folder?

**Comment by wabiloo** [comment]
That's actually what I ended up doing. Thanks!
