### ISSUE TITLE
poetry-dynamic-versioning fails to retrieve version with poetry 1.8.1 and 1.8.2

### ISSUE THREAD

**Issue by Dendrophylax** [mtkennerly/poetry-dynamic-versioning#174]
Hello,
I tried to upgrade my poetry version from 1.7.1 to 1.8.2 and "poetry version" just return 0.0.0 now, the plugin does not work anymore. Same with 1.8.1. 
Also, how may I enable some advanced loggin to give some more information to help with the issue?
Thank you for this cool project!

**Comment by mtkennerly** [comment]
Hi! After you updated Poetry, did you uninstall and reinstall the plugin? And did you make sure to include the `[plugin]` feature, as in `poetry self add "poetry-dynamic-versioning[plugin]"`?

> Also, how may I enable some advanced loggin to give some more information to help with the issue?

This sounds like an installation/bootstrap issue, so there's no special logging, but I'd appreciate seeing the output from the plugin installation command and `poetry self show`.

**Comment by Dendrophylax** [comment]
Hello,
Thank you very much, adding poetry `self add "poetry-dynamic-versioning[plugin]"` indeed solved the issue. I misunderstood how poetry plugins work. I close the issue then. Thanks again.
