### ISSUE TITLE
Plugin installation crashes

### ISSUE THREAD

**Issue by NeffIsBack** [mtkennerly/poetry-dynamic-versioning#176]
Hi!
I am trying to add the plugin to poetry, but it fails mid installation with the following error:
![image](https://github.com/mtkennerly/poetry-dynamic-versioning/assets/61382599/dee88e74-216a-47f5-9f77-5bb9c7ac3cba)
This looks to me as if pypoetry uses pycparser as well, so you can't install it again...? The issue could also be that it is already installed as dependency:
![image](https://github.com/mtkennerly/poetry-dynamic-versioning/assets/61382599/c8c6d4a0-9e30-484a-9a87-721e3cfb9889)

Any idea how this problem could be resolved?

**Comment by mtkennerly** [comment]
Hi! I'm not sure why that's happening, but I can try to help narrow it down. Some questions:

* What version of Python are you using?
* What version of Poetry are you using?
* What OS/distro are you using?
* How did you install Poetry?

Based on the `python3/dist-packages` path, I'm assuming you installed Poetry via your system package manager. Is that right? I know Poetry can be a bit finicky if it's not installed in an isolated venv. The first thing I'd suggest trying is uninstall Poetry, then use [`pipx`](https://github.com/pypa/pipx) to install it in isolation (which is also the main recommendation [in the Poetry docs](https://python-poetry.org/docs/#installation)):

```
pipx install poetry
pipx inject poetry "poetry-dynamic-versioning[plugin]"
```

**Comment by NeffIsBack** [comment]
The last bullet point was a good hint! I originally installed poetry with apt and probably therefore pycparser was installed with another package before. Installing it with pipx worked fine and now i can install the plugin. Thanks for the help!
I was running py3.11.8 on kali.
