### ISSUE TITLE
Feature request: optional tag prefix for monorepo support

### ISSUE THREAD

**Issue by jfly** [mtkennerly/poetry-dynamic-versioning#178]
First off, thanks for the great tool!

We operate in a monorepo with a tag naming convention like `packagename-v1.2.3`. Currently, to support this, we need each project to specify a `pattern` in their `[tool.poetry-dynamic-versioning]` section, and this is a little finicky (it's a [long, scary regex](https://github.com/mtkennerly/dunamai/blob/v1.20.0/dunamai/__init__.py#L40-L45) that we have a make a copy of for each project in our monorepo).

Would you be open to a generic setting for this? I'm thinking something like an optional `pattern-prefix` option that we could set to `"packagename-"`, and then we wouldn't have to set `pattern` at all.

I'd be happy to send in a PR for this if you're open to it. That said, I also completely understand if this is not a feature you want to support (as I mentioned before, the existing `pattern` option does work for us, it's just a little finicky).

**Comment by mtkennerly** [comment]
I think `pattern-prefix` makes sense to add :+1:

Once these Dunamai changes are released, we can integrate them in the plugin: https://github.com/mtkennerly/dunamai/commit/f2234621882488cae2f49184bd4567e6f8e9c65d

**Comment by jfly** [comment]
Thanks, we really appreciate it!

**Comment by mtkennerly** [comment]
No problem :) Dunamai v1.21.0 and poetry-dynamic-versioning v1.3.0 are now available with the changes.
