### ISSUE TITLE
How to increase major/minor?

### ISSUE THREAD

**Issue by efaj** [mtkennerly/poetry-dynamic-versioning#183]
When using dynamic versioning, automatically the patch version (0.0.x) is increased.... however, this has led to all my projects staying forever in 0.0.x, I'm not figuring out how to bump the major or minor

Example config:
```
[tool.poetry]
version = "1.0.0"  # ignored, as documented, started with 0.0.1 since my repos didn't have tags

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "default-unprefixed"
```

**Comment by mtkennerly** [comment]
Just make a new tag when you're ready to release a new version :)

```
git tag 1.0.0 -m "Release"
```

Don't forget to `git push --tags` afterwards as well.

**Comment by efaj** [comment]
Thank you for the response, yeah this is good to close
