### ISSUE TITLE
Auto Bumping the version is not working for poetry packages

### ISSUE THREAD

**Issue by Aviputta1** [mtkennerly/poetry-dynamic-versioning#186]
Hi I am part of Devops Team, i tried to publish the poetry package to artifacroty by using poetry-dynamic-versioning. but it's not taking the git tags or git commits. here's my sample pyproject.toml
`[tool.poetry]
name = "pypi-demo"
version = "0.0.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
poetry-dynamic-versioning = "^0.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]

[tool.poetry.plugins."poetry.application.plugin"]
"poetry_dynamic_versioning" = "poetry_dynamic_versioning.logic"

build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
tag-pattern = "{version}"`

is something wrong in metadata configurations?

**Comment by mtkennerly** [comment]
Hi! A few things:

* Does it work locally?
* What build environment are you using? It may be using a shallow clone without the tags. Check this section: https://github.com/mtkennerly/dunamai?tab=readme-ov-file#other-notes
* In the CI environment, how is the plugin being installed?
* Some things in your pyproject.toml look unusual:
  * Why is `poetry-dynamic-versioning` in the `tool.poetry.dev-dependencies` section?
  * What is the `"poetry_dynamic_versioning" = "poetry_dynamic_versioning.logic"` line for?
  * `tool.poetry-dynamic-versioning.tag-pattern` is not a valid config option for this plugin.
  * Your `build-system` does not reference `poetry-dynamic-versioning`, so you're missing compatibility with PEP 517 frontends.

I recommend reviewing the setup instructions: https://github.com/mtkennerly/poetry-dynamic-versioning?tab=readme-ov-file#installation

**Comment by mtkennerly** [comment]
Let me know if you still need help sorting out the configuration. In the meantime, I'll go ahead and close this.
