### ISSUE TITLE
Your tool keeps thinking my version is 0.0.0something.

### ISSUE THREAD

**Issue by jymchng** [mtkennerly/poetry-dynamic-versioning#188]
Error message

```
(.venv) root@vmi1175516:~/python_projects/simple-python-template# poetry version minor
Bumping version from 0.0.0-post.1+02530c5 to 0.1.0
(.venv) root@vmi1175516:~/python_projects/simple-python-template# poetry version minor
Bumping version from 0.0.0-post.1+02530c5 to 0.1.0
```

https://github.com/jymchng/simple-python-template

The repo is as above.

**Comment by edgarrmondragon** [comment]
I think you got the `tool.poetry-dynamic-versioning` table commented out in your project :)

**Comment by mtkennerly** [comment]
Looks like it was commented out in this commit: https://github.com/jymchng/simple-python-template/commit/4abba0188af4a22d6c902677b24e2ffadaae242a , shortly after opening this ticket.

The main issue I see is that there are no Git tags. The plugin looks for a Git tag like `v1.2.3`, and the latest version-like tag is used as the base for the dynamic version. When there are no tags (or none of them match the expected pattern), then 0.0.0 is used as a default base.

**Comment by mtkennerly** [comment]
Also, just to be clear, the Poetry bump commands don't really make sense to use in conjunction with this plugin. When you release a new version, you would just do `git tag v1.2.3 -m "Release" && git push --tags`.

**Comment by jymchng** [comment]
> Looks like it was commented out in this commit: [jymchng/simple-python-template@4abba01](https://github.com/jymchng/simple-python-template/commit/4abba0188af4a22d6c902677b24e2ffadaae242a) , shortly after opening this ticket.
> 
> The main issue I see is that there are no Git tags. The plugin looks for a Git tag like `v1.2.3`, and the latest version-like tag is used as the base for the dynamic version. When there are no tags (or none of them match the expected pattern), then 0.0.0 is used as a default base.
> 
> Since your project is a template, 0.0.0 is normal. The end users of your template would then create their own Git tags and start to see the dynamic version being populated based on their tags.

Thank you for your reply.

In this case, would you mind sharing a short guide on exactly how I can / should use this plugin during the development process?

Thank you.

**Comment by mtkennerly** [comment]
The [README](https://github.com/mtkennerly/poetry-dynamic-versioning/blob/master/README.md) should have the info you need, but if something's not clear or you run into a specific problem, I can try to help :)
