### ISSUE TITLE
Document git version needed

### ISSUE THREAD

**Issue by louwers** [mtkennerly/poetry-dynamic-versioning#19]
I got the following error when using `poetry-dynamic-versioning`:

```
Error: The command 'git tag --merged HEAD --sort -creatordate' returned code 129. Output:
error: unknown option `merged'
```

This feature was introduced in git 2.7.2 (released in 2016, long time ago, but not available on some platforms yet).

**Comment by mtkennerly** [comment]
Thanks for the heads-up - I'll add a note about that. It looks like 2.7.0 included it as well, based on [the tags that include this commit](https://github.com/git/git/commit/5242860f548d1869ac2779726ad496f0ae8ab5ca).

![image](https://user-images.githubusercontent.com/4934192/90631104-26592b00-e1f0-11ea-93a5-a09d33adba6b.png)

**Comment by louwers** [comment]
Thanks for the swift response. Seems like it! :+1:

**Comment by mtkennerly** [comment]
I've added the version itself to the Dunamai README and put a note in the plugin README to refer to the other page for the latest info.
