### ISSUE TITLE
Incorrect version tag picked when having multiple tags for a git hash

### ISSUE THREAD

**Issue by bcapitanu** [mtkennerly/poetry-dynamic-versioning#191]
Running into the following issue:

```
$ git tag --points-at HEAD
1.4.0
1.4.1-alpha.1
```
So I have two tags pointing at the same git ref. The older tag is `1.4.0`, the newer tag is `1.4.1-alpha.1`.

When I use `poetry version` (or "build"), the older tag (1.4.0) gets picked, not the newer one.
I tried setting `latest-tag = true` but that hasn't helped -- still 1.4.0 gets picked.

```
$ git show-ref --tags
...
fec43f3ab300071e41e86dc44656675fcfd8005d refs/tags/1.4.0
fec43f3ab300071e41e86dc44656675fcfd8005d refs/tags/1.4.1-alpha.1
```

Maybe it would be nice to implement a "sort" option that could let `poetry` pick the first match according to the sort.

```
$ git tag --sort=-v:refname --points-at HEAD
1.4.1-alpha.1
1.4.0
```
the supported sort options in `git` are:
- "refname" (lexicographic order),
- "version:refname" or "v:refname" (tag names are treated as versions).

maybe something like:
```
[tool.poetry-dynamic-versioning]
tag-sort = ["name" | "version"]
```

**Comment by bcapitanu** [comment]
Hmm... this is coming from `dunamai`. 

```
$ dunamai from git --style semver --pattern default-unprefixed
1.4.0
```

**Comment by mtkennerly** [comment]
Hi! This can happen with lightweight tags, since they don't record their creation timestamp. Annotated tags don't have that problem:

```
git tag 1.4.0 -m "Message here"
```

**Comment by bcapitanu** [comment]
as it happens, the two tags are actually annotated tags, but for some reason they have the same timestamp.

```
$ git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags
...
refs/tags/1.4.0 Thu Aug 8 12:15:16 2024 -0500
refs/tags/1.4.1-alpha.1 Thu Aug 8 12:15:16 2024 -0500
```
The tags were created via the "Create release" functionality in Github.  They were NOT actually created at the same time -- they are at least 4-5 weeks apart, but no idea why the timestamp is the same.

Anyway -- the original question stands -- would you be in favor to have some kind of "tag-sort" configuration to mitigate situations like this?

**Comment by bcapitanu** [comment]
just to clarify -- the new tag `1.4.1-alpha.1` was created weeks after the `1.4.0` tag, but without any actual repo changes (so it's on the same commit ref)

**Comment by mtkennerly** [comment]
> as it happens, the two tags are actually annotated tags, but for some reason they have the same timestamp.

What are their `taggerdate`? Dunamai prefers `taggerdate` -> `committerdate` -> `creatordate`.

Also, for reference, what Git version are you using?

> Anyway -- the original question stands -- would you be in favor to have some kind of "tag-sort" configuration to mitigate situations like this?

I would prefer to find another solution (via the Git metadata, e.g., `taggerdate`), but if that doesn't work out, then I would be open to something like that.
