### ISSUE TITLE
Plans to implement of semver versioning style support

### ISSUE THREAD

**Issue by arshvin** [mtkennerly/poetry-dynamic-versioning#192]
Hi team! 
Let's imagine I need to put version of my product to `0.0.1-development`, if the the poetry project is build from `development` branch, and `0.0.1-feature-whatever`, if it's build from `feature/whatever` branch, etc. Versions like `0.0.1-development`, `0.0.1-feature-whatever`, `0.0.1` are compliant to `semver` spec. I even check it with help of online checkers.
I've tried to use the feature of version providing with help of file (`[tool.poetry-dynamic-versioning.from-file]` section), but `poetry-dynamic-versioning` plugin, even with setting `style = "semver"` falls in following [line](https://github.com/mtkennerly/poetry-dynamic-versioning/blob/master/poetry_dynamic_versioning/plugin.py#L96), because of it's using only `pep440` version parser.
My question is: are you plan implementing of `semver` style versioning approach, or not?
Thanks in advance!

**Comment by arshvin** [comment]
> Hi! Unfortunately, although poetry-dynamic-versioning itself can produce Semantic Versioning, it's still limited by what Poetry will ultimately accept. I would recommend bringing up your use case with the Poetry team.

Yes...I've tried to do some little investigation of which "dirty hack" could be applied, with help of, for example [semver](https://pypi.org/project/semver/) library, but finally, expectedly, an exception happens somewhere inside of poetry library, because of different interfaces. And there are no any other version parsers except of pep440, inside of poetry lib code base, as far as I can see.

**Comment by mtkennerly** [comment]
Looks like the Poetry ticket was closed as something they won't implement, so I don't think there's anything the plugin can do here, I'm afraid.
