### ISSUE TITLE
Error when running plugin in dockerized environment  - `malformed object name main`

### ISSUE THREAD

**Issue by zygm0nt** [mtkennerly/poetry-dynamic-versioning#193]
I've ran into an issue with the use of plugin in a dockerized CI job. 
I've installed the plugin with the following command:

```
$POETRY_HOME/bin/pip install --user poetry-dynamic-versioning
```

but this produces the following error:

```
$ poetry version
The command 'git for-each-ref "refs/tags/**" --merged main --format "%(refname)@{%(objectname)@{%(creatordate:iso-strict)@{%(*committerdate:iso-strict)@{%(taggerdate:iso-strict)"' returned code 128. Output:
fatal: malformed object name main
```

All this works correctly when tested on my local machine, but there I'm able to install the plugin with `pipx`.

Any hints as to what might be causing this strange behavior?

**Note**: I've tried installing with `poetry self add "poetry-dynamic-versioning[plugin]"` but this caused next steps to fail due to `poetry not found` error. That's why I've switched to `pip install` method.

**Comment by zygm0nt** [comment]
That was my first guess, and I've changed CI settings to do a `clone`. This is even recognized by git.

I can see that when executing:

```
$ git rev-parse --is-shallow-repository || git fetch --unshallow
false
```

**Comment by mtkennerly** [comment]
Huh, that's weird then. Could you try these commands in the container and compare with your local system?

```
git branch
git log -n 1 main
```

You could also try removing the `tag-branch` plugin option, unless you specifically need it for your use case.

**Comment by zygm0nt** [comment]
Removing `tag-branch` was exactly what helped here.

I think it's ok for now, so closing this issue.
