### ISSUE TITLE
_get_and_apply_version fails if not in a VCS environment

### ISSUE THREAD

**Issue by bolliger32** [mtkennerly/poetry-dynamic-versioning#196]
My understanding is that this line should allow you to fall back to a default version (i.e. as specified in pyproject.toml): https://github.com/mtkennerly/poetry-dynamic-versioning/blob/f1f56a01db2c8d909c7bb42838634e31e39517e9/poetry_dynamic_versioning/__init__.py#L258-L262

However, I think when trying to install from source via `poetry build` or `pip install -e .` , `_get_version()` will already raise an error b/c it can't find the appropriate VCS project. You get `RuntimeError: This does not appear to be a {vcs} project`. Am I understanding the functionality correctly? Or is there some configuration settings I could use to ensure that we fall back to a version number if there is no VCS present to use?

**Comment by mtkennerly** [comment]
Hi! That code snippet is mainly talking about installing from an sdist or wheel created by `poetry build`, where a static copy of the dynamic version would be injected into the artifact.

If you're installing from the original source code (but without the VCS history), then there are some environment variables you can use to force a version: https://github.com/mtkennerly/poetry-dynamic-versioning?tab=readme-ov-file#environment-variables . `_get_version()` can an early return if those are set:

https://github.com/mtkennerly/poetry-dynamic-versioning/blob/54d9d15b3841630d509b69c74df5855e0ae60554/poetry_dynamic_versioning/__init__.py#L476-L478

**Comment by bolliger32** [comment]
Gotcha makes sense. I saw those env variables but figured there might be a way to configure a fallback back without needing them. Sounds like the env variables are the way to go though thanks!
