### ISSUE TITLE
Be clearer on how end user can use this?

### ISSUE THREAD

**Issue by jymchng** [mtkennerly/poetry-dynamic-versioning#200]
For example, to be explicit that when `git tag v0.1.0` is used, the plugin automatically updates the `__version__` variable in some `.py` files and `tool.poetry.package.version`.

In the current README.md, it doesn't say exactly what does it do.

**Comment by mtkennerly** [comment]
Hi! Thanks for raising this concern. I've added a clarification in b7a8d3f43ae853fb1e186db1d336e4df23201425 :)
