### ISSUE TITLE
Issue when used inside a Jenkins pipeline

### ISSUE THREAD

**Issue by Billal-B** [mtkennerly/poetry-dynamic-versioning#24]
When attempting to use dynamic versioning manually using the command `poetry-dynamic-versioning` in a Jenkins pipeline, I get the following error : 
`[ValueError]
invalid literal for int() with base 10: "warning: refname 'v0.0.11' is ambiguous.\n0"`

I think it's caused by the following lines : https://github.com/mtkennerly/dunamai/blob/master/dunamai/__init__.py#L338-L339
L338 we retrieve a message which is actually "warning: refname 'v0.0.11' is ambiguous.\n0"
L339 we try to cast that message to an integer.

As for why this warning occur, it's because I use Jenkins and tags to make a release. First I create a git tag (in this case `v0.0.11`), then I schedule a Jenkins build to do various stuff (among them call `poetry-dynamic-versioning`). However, during initialization, Jenkins does `git checkout -b v0.0.11 8945d639f97f7e5a00364o249f844ee33e93a2e4` so a branch named `v0.0.11` is created.

**Comment by mtkennerly** [comment]
Thanks for the detailed info! That makes sense. I've used it with Jenkins before, but the release branches were named like `release/v0.0.11`, which I suppose avoids the conflict. I'll see if I can use the longer `refs/tags/v0.0.11` form in Dunamai to avoid this issue. In the meantime, would using a `release/` prefix on the branch be a viable workaround for you?

**Comment by Billal-B** [comment]
Thanks for the reply ! Unforatunately I don't have the hand on how branches are named so that workaround won't do it for me. 
This is not an urgent matter, so I guess I'll just wait for the fix for now

**Comment by mtkennerly** [comment]
@Billal-B This is now fixed in [Dunamai v1.3.1](https://github.com/mtkennerly/dunamai/releases/tag/v1.3.1). Could you update and let me know if you still see any issues? (no need to update the plugin)

**Comment by Billal-B** [comment]
@mtkennerly It's working fine now, thanks a lot !
