### ISSUE TITLE
pip sees correct version number but `__version__` is not substituted on `poetry install`

### ISSUE THREAD

**Issue by DerPhysikeR** [mtkennerly/poetry-dynamic-versioning#25]
Hi

When I use `poetry install` to work on my package, `pip list` shows my package with the correct version number, but the `__version__` variable is not set, although I have the following lines in my `pyproject.toml`.

```
 [tool.poetry-dynamic-versioning.substitution]
 files = ["packagename/__init__.py"]
```

When I create a wheel with `poetry build` the substitution is performed as expected.

Is this intended behaviour, that the defined substitutions are not performed when using `poetry install` although the correct version number is visible for pip, or is it a bug?

**Comment by mtkennerly** [comment]
Hi! This is intended. `poetry build` and `poetry install` technically both trigger the file substitutions, but they also both revert those changes afterwards to avoid being committed. The idea is that the modified files only need to end up in the wheel or other distributed artifacts, but they don't need to stay in your working folder or in the repository history.

**Comment by DerPhysikeR** [comment]
Ahh, now I understand. In an editable install the version variable is of course read from the files as they lie in the directory, while the version number for pip is only read once, during the installation procedure where it is substituted.
Sorry for bothering you and thank you for the quick answer!
Thank you for the very useful project, btw!

**Comment by mtkennerly** [comment]
No worries! I'm glad you like it \:D
