### ISSUE TITLE
Support for poetry 1.1.0, poetry-core

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#26]
Hi 🍻

I know it's early days for poetry 1.1.0 (not even out yet). But I just tried using poetry-dynamic-versioning 0.9.0 with poetry 1.1.0rc1 (with poetry-core 1.0.0rc2 as build-system).

During a `poetry install`, I can se git URLs like this (which shows the appropriate semver with poetry 1.0.10):
```
• Installing pkg1 (0.0.0 141bd6e)
```

In this case, `pkg1` is actually using the build system `poetry>=0.12`, so maybe this is simply an incompatible combo?

Figured I'd report it here.

Thanks for your excellent work on this plugin/hack and on Dunamai! ❤

**Comment by mtkennerly** [comment]
v0.10.0 of the plugin is now able to patch `poetry-core` used as a standalone build system. Let me know if you see any issues with it in your setup.

**Comment by fredrikaverpil** [comment]
Thank you so much @mtkennerly ❤️
I will give this a try either today or next week and provide you with any feedback I may have!
