### ISSUE TITLE
Is it possible to choose the behavior when not installed?

### ISSUE THREAD

**Issue by max-sixty** [mtkennerly/poetry-dynamic-versioning#28]
Currently, if `poetry-dynamic-versioning` isn't installed on a system, the version doesn't change from `0.0.0`.

I can't immediately see how [PEP 518](https://www.python.org/dev/peps/pep-0518/) handles the case when something in `requires` isn't present.

Is it possible to elect to raise an error? Or even install `poetry-dynamic-versioning`?

**Comment by mtkennerly** [comment]
Are you mainly concerned about end user installs or developer installs? There are a few scenarios to consider:

* For end user installs from source, Pip respects the build-system `requires` and will install the plugin if it's listed there.
* For end user installs from a wheel, the version is encoded in the wheel statically, so the plugin isn't necessary for the end user.
* For developer installs of the current project's dependencies, Poetry respects the dependencies' build-system info.
* For developer installs of the current project itself, I don't *think* Poetry looks at the build-system info, but I could be mistaken.

If the last scenario is the one you're worried about, there's not really any way to change the behavior if the plugin isn't present. Long-term, this should be solved once Poetry has official support for plugins.

**Comment by max-sixty** [comment]
Thanks! It's the last scenario. 

I think I understand now — `poetry-dynamic-version` can change the version when it's installed, but it can't force poetry to raise an error when it's not installed. So the project gets installed as `0.0.0` when `poetry-dynamic-version` isn't installed.

Thanks!
