### ISSUE TITLE
Installing with --no-root still requires vcs

### ISSUE THREAD

**Issue by max-sixty** [mtkennerly/poetry-dynamic-versioning#29]
We install dependencies in a docker build step prior to installing the python package. This allows docker to cache the dependency installations, which is useful given their cost and frequency of change.

I've tried using `--no-root` to ensure only the dependencies are installed, and hoping the `.git` path wouldn't be required by `poetry-dynamic-versioning`. But it still seems to raise an error:

```
Step 17/22 : RUN poetry config virtualenvs.create false     && poetry config experimental.new-installer false     && poetry install --no-root --no-interaction --no-ansi     && poetry check
 ---> Running in 2cf1426e52dd

  RuntimeError

  Unable to detect version control system.

  at /usr/local/lib/python3.8/site-packages/dunamai/__init__.py:145 in _detect_vcs
      141│             if shutil.which(command.split()[0]):
      142│                 code, _ = _run_cmd(command, codes=[])
      143│                 if code == 0:
      144│                     return vcs
    → 145│         raise RuntimeError("Unable to detect version control system.")
      146│
      147│
      148│ @total_ordering
      149│ class Version:
The command '/bin/sh -c poetry config virtualenvs.create false     && poetry config experimental.new-installer false     && poetry install --no-root --no-interaction --no-ansi     && poetry check' returned a non-zero code: 1
```

**Comment by mtkennerly** [comment]
It's not ideal, but there are a couple of ways you could work around this currently:

* Don't install the plugin until after the `--no-root` command.
* Disable and re-enable the plugin by renaming its config section:

  ```
  sed -i 's/tool.poetry-dynamic-versioning/tool.poetry-dynamic-versioning-x/' pyproject.toml
  ...
  sed -i 's/tool.poetry-dynamic-versioning-x/tool.poetry-dynamic-versioning/' pyproject.toml
  ```

The plugin doesn't currently have any awareness of the Poetry CLI to check for `--no-root`, and I'm not sure if there's a robust/futureproof way to approach that within the current limitations. A compromise might be to temporarily disable the plugin by setting an environment variable, but if this is an uncommon issue, then I'd probably rather wait to address it once Poetry has official plugin support (assuming that has some functionality to recognize this case).

**Comment by max-sixty** [comment]
OK, that makes sense. The first suggestion is great, I'll do that.

I had hoped there might be a way to only check for the version if installing the current project — no stress that that's not possible.

Thanks!
