### ISSUE TITLE
poetry-dynamic-versioning breaks functionality of some poetry commands (e.g. poetry add, poetry remove) which modify pyproject.toml

### ISSUE THREAD

**Issue by lmoretto** [mtkennerly/poetry-dynamic-versioning#3]
Hi,
when poetry-dynamic-versioning is enabled for a project, some poetry commands do not work as expected.

For instance, the expected result of `poetry add <dependency>` or `poetry remove <dependency>` commands is to modify the content of `pyproject.toml` file with the new/removed package dependencies.

I think the reason is that, upon deactivation, poetry-dynamic-versioning completely restores the original contents of `pyproject.toml`, thus discarding any legitimate modifications to the file performed by poetry.

Would it make sense to only restore the original version field, and keep any other modifications?
If so, I can provide a PR for this.

Thanks and best regards,
Luca

**Comment by mtkennerly** [comment]
Thanks for reporting this! Yes, I think just restoring the version field would be the right way to go. A PR would absolutely be welcome if you're interested.

**Comment by mtkennerly** [comment]
The fix for this is now available in release v0.3.1.
