### ISSUE TITLE
Broken subdependency?

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#31]
This started happening today. The server is equipped with a git version which does not support the --porcelain value.

If I remove `poetry-dynamic-versioning==0.10.0` from the pip install command, the issue is gone, and I'm wondering if it can be any of the subdeps of poetry-dynamic-versioning that could be causing this...?

I prefer not to update git at this point in time, if possible. Would it be possible to pin a subdep, if that is causing this?

```bash
source venv/bin/activate
pip install poetry==1.0.10 poetry-dynamic-versioning==0.10.0
poetry install -v

Installing dependencies from lock file

[RuntimeError]
The command 'git status --porcelain=v1' returned code 129. Output:
error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns

```

**Comment by fredrikaverpil** [comment]
It's because of dunamai, which was released about 4 hours ago.

**Comment by mtkennerly** [comment]
Yeah, the use of `--porcelain` is coming from Dunamai (1.4.0). For reference, what version of Git are you using? Officially, Dunamai requires Git 2.7.0 or newer, so if yours is newer than that and doesn't support `--porcelain`, I'll try to find another implementation instead.

**Comment by fredrikaverpil** [comment]
```
$ git --version
git version 2.7.4
```

**Comment by mtkennerly** [comment]
Alright, I didn't realize `--porcelain` was a newer feature, so I'll consider that a bug (unintentional minimum Git version change) and adjust the implementation. Sorry about that.

**Comment by mtkennerly** [comment]
Could you please confirm if `git status --porcelain` works? It looks like `--porcelain` without a value would work, just not `--porcelain=v1` with a value.

**Comment by fredrikaverpil** [comment]
Sounds great, no worries. :)

Yes, `git status --porcelain` does at least not give me an error. Not giving me anything (so I assume it works).

**Comment by fredrikaverpil** [comment]
In case anyone is hit by this and find this issue. You can mitigate this like so for now:

```
pip install poetry==1.0.10 poetry-dynamic-versioning==0.10.0 dunamai==1.3.1
```

**Comment by mtkennerly** [comment]
Just released v1.4.1 to fix this. Let me know if you see any more issues.

**Comment by fredrikaverpil** [comment]
I'll try this shortly!

**Comment by fredrikaverpil** [comment]
Very nice, it just works now. No need for downgrading dunamai :)
Many thanks! ❤️ 🤘
