### ISSUE TITLE
poetry 1.0.10 build/shell/install/update does not trigger versioning

### ISSUE THREAD

**Issue by pvelesko** [mtkennerly/poetry-dynamic-versioning#34]
I have this in my pyprojects.toml :
```
[build-system]
requires = ["poetry>=1.0.10", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
latest-tag = true
pattern = "^(?P<base>\\d+\\.\\d+\\.\\d+)"
format = "{base}"
# bump = true

[tool.poetry-dynamic-versioning.substitution]
files = ["*/settings.py"]
```

Neither of the poetry commands trigger anything but using the CLI `poetry-dynamic-versioning` works as expected.

**Comment by mtkennerly** [comment]
It's hard to say what's going on here, so let's start with some questions:

* What OS do you use?
* What Python version do you use?
* Does `pip list` mention poetry_dynamic_versioning?
  * If so, what version is it?
* Does `poetry run pip list` mention poetry_dynamic_versioning?
  * If so, what version is it?
* What output do you get for these (or the equivalent in your shell):
  * `which python`
  * `which pip`
  * `which poetry_dynamic_versioning`
  * `which poetry`
  * `poetry run which python`
  * `poetry run which pip`
  * `poetry run which poetry_dynamic_versioning`

**Comment by mtkennerly** [comment]
I'm going to close this for now since I need the above info in order to narrow down what may be happening on your system, but we can reopen if you have a chance to get that info.

**Comment by pvelesko** [comment]
I missed the notification of your first reply, @mtkennerly  but it seems the issue was on my end as it works now. I can't immediately tell what changed in my system but will follow up if I do.
