### ISSUE TITLE
Warning/Error not thrown when failed to get git tag information

### ISSUE THREAD

**Issue by pvelesko** [mtkennerly/poetry-dynamic-versioning#36]
Ran into an issue where the version was not getting bumped correctly inside docker builds. 
It turned out that `COPY . .` did not copy all the `.git` files/dirs/subdirs such that doing `git tag` did not return anything. 

I think a warning/error should be thrown in this case. 

Version `0.12.1`

**Comment by mtkennerly** [comment]
The behavior here is actually by design so that you can use the plugin in a brand new repository that really doesn't have any tags yet. Once there's at least one tag, then it'll give you an error if none of the tags can be used for versioning, though.
