### ISSUE TITLE
Official plugin system

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#39]
Hey, have you seen this? 😊
https://github.com/python-poetry/poetry/pull/3733

**Comment by mtkennerly** [comment]
I did! It's pretty exciting \:D Looking forward to updating this to take advantage of it.

**Comment by fredrikaverpil** [comment]
Looks like it's been merged to master! 😃

**Comment by mtkennerly** [comment]
I just released v1.0.0b1 using the official plugin interface. I'd appreciate feedback from anyone who wants to try it out. It requires Poetry 1.2.0a2+ and Python 3.6+.

The one issue I know right now is that the plugin behavior doesn't trigger for dependencies, only for the main project. I still need to research how to implement that.

Updated documentation: https://github.com/mtkennerly/poetry-dynamic-versioning/blob/release/v1.0.0/README.md

**Comment by fredrikaverpil** [comment]
@mtkennerly that's awesome news! 🍾 🎉 
I'm (somewhat unfortunately) not using this project anymore, as I've moved on to another company. I therefore have nothing to test this with at the moment.

**Comment by mtkennerly** [comment]
No worries! Thanks for all the feedback you gave me while you were still using it :)

**Comment by Darsstar** [comment]
After probably an hour worth of first contact: so far no issues!

**Comment by layday** [comment]
Will v1 be usable without Poetry (i.e. with `poetry-core` only)? My understand is that Poetry plug-ins are not implemented in the backend, meaning that building a package with dynamic versioning would require installing all of the Poetry CLI's dependencies.

**Comment by Darsstar** [comment]
> The one issue I know right now is that the plugin behavior doesn't trigger for dependencies, only for the main project. I still need to research how to implement that.

Could that be because of https://github.com/pypa/pip/pull/11022?

**Comment by mtkennerly** [comment]
> Will v1 be usable without Poetry (i.e. with `poetry-core` only)? My understand is that Poetry plug-ins are not implemented in the backend, meaning that building a package with dynamic versioning would require installing all of the Poetry CLI's dependencies.

Right, the official plugin system means it will depend on Poetry itself, not just poetry-core. I'll probably end up releasing a slimmed down version of the existing implementation as `poetry-core-dynamic-versioning` for that use case.

> Could that be because of https://github.com/pypa/pip/pull/11022?

I think it's just that the Poetry plugin behavior is designed to only affect the active project. I found a workaround, and although it still relies on monkey patching, at least it doesn't need to do import shenanigans with a pth file.

**Comment by mtkennerly** [comment]
> The one issue I know right now is that the plugin behavior doesn't trigger for dependencies, only for the main project. I still need to research how to implement that.

This is now fixed in v1.0.0b3.

**Comment by mtkennerly** [comment]
As mentioned in https://github.com/mtkennerly/poetry-dynamic-versioning/issues/39#issuecomment-1106182990, I'm now releasing two separate packages:

* `poetry-dynamic-versioning` (using the import hack) - just published v0.15.0
* `poetry-dynamic-versioning-plugin` (using the official plugin system) - just published v0.1.0

I'd only recommend having one installed at a time, but they do attempt to play nice with each other. These new releases are just to reflect the unified code base, so pdv v0.14.1 and v0.15.0 should behave the same as each other, and so should pdv v1.0.0b3 and pdv-plugin v0.1.0.

**Comment by mtkennerly** [comment]
I think the new `poetry-dynamic-versioning-plugin` is in a good state, so I'm going to go ahead and close this. I'll keep monitoring Poetry 1.2.x (pre-)releases for any changes that may be necessary.
