### ISSUE TITLE
poetry-dynamic-versioning doesn't work properly with the Python user install directory

### ISSUE THREAD

**Issue by alberthier** [mtkennerly/poetry-dynamic-versioning#43]
`poetry-dynamic-versioning` doesn't seem to work properly when installed in the Python user install directory (`$HOME/.local` by default on Linux). Packages get installed in this folder when installing with `pip --user` (see [the documentation](https://pip.pypa.io/en/stable/user_guide/#user-installs))

The issue can be reproduced with the official `python:3.8` docker image:

```
$ docker run -it python:3.8 /bin/bash
root@1924046cfe65:/# export PATH=$HOME/.local/bin:$PATH
root@1924046cfe65:/# pip install --user poetry
Collecting poetry
  Downloading poetry-1.1.5-py2.py3-none-any.whl (171 kB)
[snip...]

root@1924046cfe65:/# poetry --version
Poetry version 1.1.5
root@1924046cfe65:/# pip install --user poetry-dynamic-versioning
Collecting poetry-dynamic-versioning
  Downloading poetry_dynamic_versioning-0.12.4-py3-none-any.whl (12 kB)
[snip...]

root@1924046cfe65:/# poetry --version
Error processing line 1 of /root/.local/lib/python3.8/site-packages/zzz_poetry_dynamic_versioning.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/root/.local/lib/python3.8/site-packages/poetry_dynamic_versioning/__init__.py", line 15, in <module>
      from dunamai import (
    File "/root/.local/lib/python3.8/site-packages/dunamai/__init__.py", line 4, in <module>
      import pkg_resources
  ModuleNotFoundError: No module named 'pkg_resources'

Remainder of file ignored
Poetry version 1.1.5
```

When installing the packages without the `--user` `pip` flag, it works properly.

**Comment by mtkennerly** [comment]
Thanks for reporting this. I'm not exactly sure why this doesn't work, but I imagine it's a loading sequence issue because of the plugin's \*.pth file. Since official plugin support has now landed in Poetry master, which will eliminate the need for the \*.pth file, I think it may make sense at this point just to wait for the next Poetry release. In the meantime, please omit the `--user` flag as a workaround.

**Comment by alberthier** [comment]
I removed the `--user` flag for now.

Indeed the pth file loading is probably the issue here. As poetry's plugin support should solve this issue, I think it can be closed.
