### ISSUE TITLE
Add an option to bump the version only if not on tag.

### ISSUE THREAD

**Issue by gbdlin** [mtkennerly/poetry-dynamic-versioning#44]
Current behavior of generating the version number, regarding the `bump` setting and being on a commit without a version tag or with a version tag, looks as follows:

- When on a commit without a version tag and `bump = True`, version number will be bumped and a `.dev` with a distance from the version tag and a commit hash will be added.
- When on a commit without a version tag and `bump = False`, version number will not be bumped and a `.post` with a distance from the version tag, a `.dev0` and a commit hash will be added
- When on a commit with a version tag and `bump = True`, version number will be bumped, no other changes will be made
- When on a commit with a version tag and `bump = False`, version number will not be bumped, version used "as is" from the tag.

But there is no option to mix the first and the last behavior (to achieve similar version number generation `setuptools-scm` has).

**Comment by mtkennerly** [comment]
Thanks for reporting this! This was an oversight in the implementation, so I don't think there's a need to add an option. I'll fix it so that, if it's on a tagged commit, then it won't bump.

**Comment by mtkennerly** [comment]
This is now fixed in v0.12.5.

**Comment by gbdlin** [comment]
Pretty sure it was fixed only for `format-ninja`, not for normal `format` option.

**Comment by mtkennerly** [comment]
Sorry about that; you're absolutely right. I've just released v0.12.6 to address it.
