### ISSUE TITLE
Working with docker images

### ISSUE THREAD

**Issue by dieggoluis** [mtkennerly/poetry-dynamic-versioning#45]
First of all, thank you for this great library!

I'm using `poetry` to build and install a library in a docker image. As poetry-dynamic-versioning gets some metadata from `.git`, I have to copy this folder before running `poetry install` which I usually try to avoid to speed up building time thanks to the docker caching system. Is there a way of passing parameters to poetry-dynamic-versioning so that I don't need to copy the entire `.git`folder during docker build?

**Comment by mtkennerly** [comment]
The closest thing right now would be to run the `poetry-dynamic-versioning` CLI on your host machine to persist the version in the files before copying them into the container. Would that work for you? You would just need to revert the changes that the CLI made on the host machine afterwards (`git checkout -- .`).

**Comment by dieggoluis** [comment]
That might work locally but would require some changes in our CI. Thanks for the answer
