### ISSUE TITLE
Bump Jinja2 to allow for Jinja2 3.x

### ISSUE THREAD

**Issue by whardier** [mtkennerly/poetry-dynamic-versioning#51]
We have projects that depend on Jinja that also use this project and we are planning on using 3.x.  It's a mess.. I know.. 

Please review new Jinja2 3.x for inclusion into this project.  Alternatively I can help provide patching to remove Jinja2 from this project or possibly set Jinja2 as an extra dep since it is not required.

**Comment by whardier** [comment]
#52

**Comment by mtkennerly** [comment]
Thanks for raising this concern. The timing here is kind of interesting:

* poetry-dynamic-versioning still supports Python 3.5,
* Jinja2 3.0.x no longer supports Python 3.5,
* Poetry 1.1.x still supports Python 3.5, but 1.2.x will no longer support it (and there's already a 1.2.0a1 available, so it may not be long).

Fortunately, Poetry does allow you to configure different dependency ranges based on [environment markers](https://python-poetry.org/docs/dependency-specification/#using-environment-markers), so this is manageable.

As part of Poetry 1.2.0, the official plugin system will become available as well (#39), and then PDV and its dependencies might be installed in such a way that they wouldn't conflict with your project's use of a different Jinja2 version anyway (although I'm not 100% sure on that). Still, in the meantime, I agree it's best to update this.

**Comment by mtkennerly** [comment]
This is now addressed in v0.13.0. Let me know if you run into any further issues with it.
