### ISSUE TITLE
Freezing when doing `poetry publish` while dynamic versioning is enabled

### ISSUE THREAD

**Issue by darkvertex** [mtkennerly/poetry-dynamic-versioning#59]
The upload prints 0% then 100% but doesn't finish serverside.

If I set `enable = false` in my `[tool.poetry-dynamic-versioning]` block (and manually set the version tag properly) it publishes/uploads without a hitch. 🤔

**Comment by mtkennerly** [comment]
I'm not currently able to reproduce this, using:

* Python 3.7.9
* Poetry 1.1.12 (installed via `pip`)
* poetry-dynamic-versioning 0.14.0
* Windows 11 with Git Bash

I was able to upload [a package](https://test.pypi.org/project/mtkennerly-test-project/0.14.0/) to test.pypi.org without any freezing. If this issue still occurs for you, could you please tell me your environment?
