### ISSUE TITLE
`dirty` option doesn't affect anything

### ISSUE THREAD

**Issue by zmarffy** [mtkennerly/poetry-dynamic-versioning#68]
Alternatively, it is quite possible I am misunderstanding the point of the option.

Steps to reproduce:

1. Add this to `pyproject.toml.
```
[tool.poetry-dynamic-versioning]
enable = true
metadata = true
tagged-metadata = true
dirty = true
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}+{{ distance }}.{{ commit }}{% endif %}"
```
2. Edit something in the project's files
3. Build the project with `poetry build`
4. The resulting `sdist` and `whl` have no reference to "dirty" in them anywhere

From my understanding, one would need to reference `dirty` in `format-jinja` to have it show up in the actual version string, but the "metadata" is not the version string, right? I would assume `dirty` would show up somewhere else if I set it to `true`.

OS: macOS 12.2
Python: 3.9.9
poetry: 1.1.12
poetry-dynamic-versioning: 0.13.1

**Comment by mtkennerly** [comment]
Sorry, I'll try to make the documentation for this a bit clearer. `dirty` and `metadata` only affect the default format. When you set a custom `format` or `format-jinja`, then those are fully responsible for deciding what to include.

In the default format:

* metadata=true, dirty=false: `0.13.1.post3.dev0+8df8c18`
* metadata=true, dirty=true: `0.13.1.post3.dev0+8df8c18.dirty`
* metadata=false, dirty=true: `0.13.1.post3.dev0`

**Comment by zmarffy** [comment]
Makes sense. Appreciate the clarification.
