### ISSUE TITLE
Question: Reset version to 0.0.0 manually?

### ISSUE THREAD

**Issue by MSLeiter** [mtkennerly/poetry-dynamic-versioning#75]
Question: Is it possible to reset version to 0.0.0 after using poetry-dynamic-versioning.exe script?

i.e. after using the poetry-dynamic-versioning.exe script at the command-line, the version in pyproject.toml and any substituted version symbols is set to the repo/tag based version string.

Is there a command that will revert/cleanup this version change so that the version is reset back to 0.0.0?

**Comment by mtkennerly** [comment]
This is possible by setting an environment variable:

```
POETRY_DYNAMIC_VERSIONING_BYPASS=0.0.0 poetry-dynamic-versioning
```

Depending on your use case, you can also run `git checkout -- .` to undo the changes.

**Comment by MSLeiter** [comment]
Perfect - just to clarify for anyone finding this - at least in Git Bash:
```
export POETRY_DYNAMIC_VERSIONING_BYPASS=0.0.0 && poetry-dynamic-versioning
```
will set the environment variable to the current shell and run the script, resetting things. You should get an output with a version set to 0.0.0 and any file substitutions it finds, such as:
```
Version: 0.0.0
Files with substitutions:
  - D:\code\mca_app\jarvis\src\jarvis\__version__.py
```

You can then clear the override environment variable from the current shell with:
```
unset POETRY_DYNAMIC_VERSIONING_BYPASS
```
