### ISSUE TITLE
Difference between version and build package name

### ISSUE THREAD

**Issue by pchanial** [mtkennerly/poetry-dynamic-versioning#77]
Using poetry-dynamic-versioning-plugin, I get, 
```bash
$ poetry version --short
0.2.1.dev8+8f580db
```
and the package created with `poetry build` is `myproject-0.2.1dev8+8f580db-py3-none-any.whl`

Note the absence of dot between 0.2.1 and dev in the filename.

pyproject.toml:
```
[tool.poetry-dynamic-versioning]
enable = true
dirty = true
bump = true
style = "pep440"
```
Is it intended?

**Comment by mtkennerly** [comment]
It looks like this is an issue in Poetry 1.2.0b1, unrelated to the plugin. I've opened an issue in the Poetry repository: https://github.com/python-poetry/poetry/issues/5534
