### ISSUE TITLE
Installing plugin in global Python installation not necessary

### ISSUE THREAD

**Issue by xinofekuator** [mtkennerly/poetry-dynamic-versioning#8]
In the documentation it says:

```
Note that you must install the plugin in your global Python installation, 
not as a dependency in pyroject.toml, 
because the virtual environment that Poetry creates 
cannot see Poetry itself and therefore cannot patch it.
```

However I added it in a project with `poetry add`, installed it with `poetry install` and then ran `poetry build` (all this from inside a virtual environment of the project previously created by poetry). Checking inside the generated `tar.gz` the versions were correctly patched.

I am using version `0.6.0`

**Comment by mtkennerly** [comment]
Hmm, it's still necessary for me. I just checked on a system with:

* Poetry 1.0.5 installed via Pip (as opposed to get-poetry.py)
* Python 3.5.3
* poetry-dynamic-versioning 0.6.0
* Windows 10

Could you tell me the same info for your system?

**Comment by xinofekuator** [comment]
- Poetry 1.0.2 installed with get-poetry.py
- Python 3.7.6
- poetry-dynamic-versioning 0.6.0
- MacOS Mojave

**Comment by mtkennerly** [comment]
Thanks. I don't have access to a Mac system to try, but I tested those exact versions in a Linux VM (using the Vagrantfile in the repo), and I still had to do the step from the README. I guess it's somehow a Mac quirk? I don't know why that would be, though. Could you confirm that the output from `pip list` doesn't mention poetry-dynamic-versioning at all?

**Comment by mtkennerly** [comment]
I'm gonna close this for now since it still seems to be required on most systems.

**Comment by xinofekuator** [comment]
Sorry, forgot to reply. There was no `poetry-dynamic-versioning` when running `pip list`.
> When you mentioned "inside a virtual environment of the project previously created by poetry", if you meant that you directly activated/loaded the virtual environment in your console, then that would be how poetry-dynamic-versioning is being found.
So I did not have the lib in my system python, but I added that dependency in the toml file so when activating that venv that lib exists in that environment because it was installed by poetry as expected.

**Comment by mtkennerly** [comment]
I see, that makes sense. For now, I would still be inclined to keep the message the same, since Poetry isn't supposed to require that the venv be activated when running Poetry commands (e.g., `poetry build` and `.../activate && poetry build` should do the same thing ideally).
