### ISSUE TITLE
Version is not set on `poetry build`

### ISSUE THREAD

**Issue by MaxG87** [mtkennerly/poetry-dynamic-versioning#83]
Thank you very much for this great package and its extensive documentation. It would make some CI/CD pipelines of mine much simpler!

I think I followed the README, but it seems as if the correct version is not set when running `poetry build`. I created a minimum working example as script.

I really would appreciate if `poetry build` would update a project's version based on its git tag. If this is not the intended behaviour, I think the documentation could be a bit clearer.

```bash
#!/usr/bin/env bash

set -euo pipefail

# Probably this must be run manually, because `conda` is available only in
# interactive shells.
# conda env remove -n fresh
# conda create -yn fresh python=3.9.12 pip
# conda activate fresh
# python -m pip install poetry==1.1.13 poetry-dynamic-versioning
# # Reactivate to make sure the freshly install dependencies are available.
# conda deactivate
# conda activate

repositoryDir=$(mktemp -d)
poetry new --src --name dynver-mwe "$repositoryDir"
echo "The example project was created in $repositoryDir"
cd "$repositoryDir"

git init
git add -A
git commit -m "Initial Commit"

git apply <<EOF
diff --git a/pyproject.toml b/pyproject.toml
index 9df2908..5805575 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,6 +1,6 @@
 [tool.poetry]
 name = "dynver-mwe"
-version = "0.1.0"
+version = "0.0.0"
 description = ""
 authors = ["Max Görner"]

@@ -11,5 +11,5 @@ python = "^3.10"
 pytest = "^5.2"

 [build-system]
-requires = ["poetry-core>=1.0.0"]
+requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
 build-backend = "poetry.core.masonry.api"
EOF
git commit -am "Introduce poetry-dynamic-versioning to build-system"
git tag "v1.0.0"

poetry build

```

**Comment by mtkennerly** [comment]
Hi! In the `git apply` command, I don't see this section:

```toml
[tool.poetry-dynamic-versioning]
enable = true
```

Without that setting, the plugin won't activate. If you do have that setting and it's still not working, then it might be an issue with Conda environments, since I haven't personally tested with them before.

**Comment by MaxG87** [comment]
Awesome! I have missed that in the documentation. Thank you very much.
