### ISSUE TITLE
Poetry breaks when `poetry-dynamic-versioning[plugin]` and `poetry-dynamic-versioning-plugin` are both installed

### ISSUE THREAD

**Issue by ejd** [mtkennerly/poetry-dynamic-versioning#88]
This seems like a different issue than what #80 describes.

I have Poetry 1.2.0 installed via:

```console
$ curl -sSL https://install.python-poetry.org | python3.9 - 
```

I ran the following to get poetry-dynamic-versioning:

```console
$ poetry self add poetry-dynamic-versioning[plugin]
Using version ^0.18.0 for poetry-dynamic-versioning

Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 5 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.1)
  • Installing dunamai (1.13.0)
  • Installing jinja2 (3.1.2)
  • Installing poetry-dynamic-versioning (0.18.0)
  • Installing poetry-dynamic-versioning-plugin (0.3.2)
```

Now, when I run poetry in any way, it crashes:

```console
$ poetry -h

The command "dynamic-versioning" already exists.
```

<details>
  <summary><code>poetry -h -vv output</code></summary>

  ### `poetry -h -vv`
  ```console
$ poetry -h -vv

  Stack trace:

  5  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/cleo/application.py:329 in run
       exit_code = self._run(io)

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/console/application.py:183 in _run
       self._load_plugins(io)

  3  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/console/application.py:349 in _load_plugins
       manager.activate(self)

  2  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/plugins/plugin_manager.py:71 in activate
       plugin.activate(*args, **kwargs)

  1  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry_dynamic_versioning/plugin.py:93 in activate
       application.command_loader.register_factory(

  LogicException

  The command "dynamic-versioning" already exists.

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/console/command_loader.py:20 in register_factory
       16│     def register_factory(
       17│         self, command_name: str, factory: Callable[[], Command]
       18│     ) -> None:
       19│         if command_name in self._factories:
    →  20│             raise LogicException(f'The command "{command_name}" already exists.')
       21│ 
       22│         self._factories[command_name] = factory
       23│ 
```
</details>

**Comment by mtkennerly** [comment]
```
  • Installing poetry-dynamic-versioning (0.18.0)
  • Installing poetry-dynamic-versioning-plugin (0.3.2)
```

This part is quite strange. Installing PDV 0.18.0 shouldn't trigger anything to do with PDV-Plugin. Did you have PDV-plugin installed previously, and if so, could you try uninstalling it first? You can use `poetry self show` to double check.

**Comment by mtkennerly** [comment]
I can reproduce this by installing both variants. I've reported this to Poetry: https://github.com/python-poetry/poetry/issues/6456

In the meantime, to fix it manually, you can activate Poetry's own venv and `pip uninstall` both `poetry-dynamic-versioning` and `poetry-dynamic-versioning-plugin`.

For Poetry installed by the online script, you can look for the venv in the locations documented at the top of the script:

```
        - `~/Library/Application Support/pypoetry` on macOS
        - `$XDG_DATA_HOME/pypoetry` on Linux/Unix (`$XDG_DATA_HOME` is `~/.local/share` if unset)
        - `%APPDATA%\pypoetry` on Windows
```

For Poetry installed by `pipx`, you can use `pipx runpip poetry uninstall -y poetry-dynamic-versioning poetry-dynamic-versioning-plugin`.

After that, to keep it from reinstalling them, you should delete Poetry's internal poetry.lock and pyproject.toml files. For example, on Windows, these are located in `%APPDATA%/pypoetry`.

Finally, you can rerun `poetry self add poetry-dynamic-versioning[plugin]`.
