### ISSUE TITLE
Is there a way to restrict only the `build/publish` subcommands to call git.exe?

### ISSUE THREAD

**Issue by edsion1107** [mtkennerly/poetry-dynamic-versioning#89]
My system is Win10 LTSC(21H2).
When i try to run `git status`\`git log` in powershell, the process often block long time.So far I haven't found the regularity of this phenomenon.
I have tried reinstalling git, but modifying the configuration has not solved it.

So my problem is that the process often blocks when I run subcommands like `poetry add`, even running `portry --help`

**Comment by edsion1107** [comment]
![image](https://user-images.githubusercontent.com/1925286/190544496-e4bfcbc1-3cdd-4960-9572-e6d65f8d911c.png)

This is the problem I'm having. I have a similar problem when I submit the code in pycharm.

**Comment by mtkennerly** [comment]
Hmm, that's a weird problem. There's no way to restrict it currently, but I don't mind adding that. I think the easiest way would be with an environment variable.

**Comment by mtkennerly** [comment]
I just published [v0.19.0](https://github.com/mtkennerly/poetry-dynamic-versioning/releases/tag/v0.19.0). You can now set the `POETRY_DYNAMIC_VERSIONING_COMMANDS` environment variable to `build,publish` to do this.
