### ISSUE TITLE
Dynamic versioning not applying to build files

### ISSUE THREAD

**Issue by wagnar-woofbrok** [mtkennerly/poetry-dynamic-versioning#93]
Hello!,

I followed the README instructions to install and configure this package for a Poetry-Python3.9 project, but the build files in `dist/` are showing `-0.0.0` as their version. I'm trying to build on my `main` branch with a lightweight git tag set as `v1.0.0`.

Can you help me figure out what I'm doing wrong?

**Project Directory Structure**
```
|- common/
|-- models/
|-- services/
|-- __init__.py
|-- __main__.py
|- pyproject.toml
|- poetry.lock
```

**pyproject.toml**
```
[tool.poetry]
name = "common_vendor_code"
version = "0.0.0"
description = "Building a package with poetry dynamic versioning"
authors = ["Some Guy <autobots@email.com>"]
packages = [
    { include = "common" }
]

[tool.poetry.dependencies]
python = "^3.9"
dependency-injector = "^4.40.0"
python-dotenv = "^0.21.0"
pytest = "^7.1.3"
requests = "^2.28.1"
pydantic = "^1.10.2"
pydash = "^5.1.1"
pytest-cov = "^3.0.0"
dynaconf = "^3.1.11"
Faker = "^15.0.0"
poetry-dynamic-versioning = {extras = ["plugin"], version = "^0.19.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
# format = "v{base}"
format-jinja = "{{ serialize_semver(bump_version(base), stage, revision) }}"


[tool.poetry.scripts]
common = "common:main"
```

**Comment by mtkennerly** [comment]
I see this in your `tool.poetry.dependencies` section:

```toml
poetry-dynamic-versioning = {extras = ["plugin"], version = "^0.19.0"}
```

The plugin needs to be installed with `poetry self add`, because it needs to exist in the same Python environment as Poetry itself. Maybe you ran `poetry add` instead? That would put it in the project's virtual environment, which means Poetry won't load it as a plugin.
