### ISSUE TITLE
Question: does this plugin works with other poetry plugin?

### ISSUE THREAD

**Issue by wieczyk** [mtkennerly/poetry-dynamic-versioning#95]
Hi,

I am not sure if the taken approach works correctly with other plugins. In my private project I am depending on my plugin and dynamic-versioning plugin. When I am printing `even.command.poetry.package.version' I see the version from TOML file.

Both plugins are ApplicationPlugin and are based on event subscription. I think that my event handler was executed before even handler from dynamic versioning plugin, where the versioning patch is applied. Does it make sense? Is it possible to compose plugin with poetry-dynamic-versioning in safe way?

**Comment by mtkennerly** [comment]
Hi! I'm not sure, but I don't think Poetry's current plugin system has a way of handling this. There would probably need to be some way to force a particular order for plugins to receive events, and there would need to be a way for plugins to exchange information. For example, this plugin sets the package version on the `Application` instance that it receives during activation, but I don't know if there's any guarantee that different plugins can see changes that other plugins make to that `Application` instance or that those changes are synchronized to other data structures. This might be worth asking in the Poetry repository.

In the meantime, maybe we can find a different solution. Does your plugin just need to know the dynamic version for the current/main project? What if this plugin set an environment variable with the version, and then your plugin waited until it saw the environment variable show up?

**Comment by mtkennerly** [comment]
Closing for now since this is more of a Poetry design constraint, but we can reopen if you'd like to explore a workaround like I mentioned. Just let me know :)
