### ISSUE TITLE
installing from zip files

### ISSUE THREAD

**Issue by onerandomusername** [mtkennerly/poetry-dynamic-versioning#97]
It would be nice to support archives of a commit in a vcs. For example, installing zipfiles of github branches. I think that in the case of a vcs backend not being detected there could have a fallback version that is used as the install version.

**Comment by mtkennerly** [comment]
I can look into doing something similar to how setuptools-scm handles this. It looks like that also works with GitHub zip downloads.

**Comment by onerandomusername** [comment]
Potentially could have a fallback version that could be used anytime the version can not be detected which could be set as `tool.poetry-dynamic-versioning.fallback-version`

**Comment by mtkennerly** [comment]
v0.21.0 adds support for some metadata files produced by `git archive` and `hg archive`. Refer to [the Dunamai documentation](https://github.com/mtkennerly/dunamai#vcs-archives) for more info. For Git, you need to make some small config changes.
