### ISSUE TITLE
poetry-dynamic-versioning for git should fail if it does find a tag

### ISSUE THREAD

**Issue by dibog** [mtkennerly/poetry-dynamic-versioning#98]
My CI/CD fetches the source code with a shallow clone.
If there were many commits after the last tags, poetry-dynamic-versioning seems
not to find the tag and does not change the existing version entry in the pyproject.toml.

Would it be possible that in this case poetry-dynamic-versioning throws an error
so the CI/CD job reports an error. Maybe add an command line flag or a config
setting for this?

**Comment by mtkennerly** [comment]
Sure, I can add an option for that. The current behavior is so you can use it in a brand new project, but the option would be good for established projects.

**Comment by mtkennerly** [comment]
With v0.21.0, you can set `strict = true` to enable this behavior.
